version: "3.9"
services:

  postgres:
    image: postgres:14.4-alpine3.16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "galleryapp"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_URL: "0.0.0.0"
    volumes:
      - postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0.9
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  # web:
  #   build: ./client
  #   ports:
  #     - 3001:3001

  api:
    build: .
    depends_on:
      - postgres
      - mongo
    links:
      - postgres
      - mongo
    ports:
      - 3003:3003
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo/galleryapp
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

volumes:
  postgres:
    driver: local
  mongodata:
    driver: local
